[package]
name = "main"
version = "0.1.0"
authors = ["Max Froehlich <max@mfro.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
byteorder = "1.3.4"
cef = { path = "../cerium-trifluoride/cef" }
lazy_static  = "1.4.0"
parselnk = "0.1.0"
percent-encoding = "2.1.0"
winapi = { version = "0.3.9", features = ["winuser", "uxtheme", "dwmapi", "libloaderapi", "shlobj", "processenv", "shellapi", "dbghelp"] }
