appx: {}
steam:
  path: C:\Program Files (x86)\Steam
start_menu: {}
custom:
  - names: [hello friend]
    target: [C:\Windows\system32\cmd.exe,/C,start cmd.exe /C echo hello friend :) ^&^& pause ^> NUL]
